[package]
name    = "r-basemapper"
version = "0.1.0"
edition = "2021"

[lib]
name       = "r_basemapper"
crate-type = ["cdylib"]
path       = "src/rust/src/lib.rs"

[dependencies]
basemapper-core = { path = "../core" }
extendr-api     = { version = "0.7", features = [] }
tokio           = { workspace = true }
once_cell       = { workspace = true }
