[package]
name    = "basemapper-core"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu        = { version = "22.1", features = ["wgsl"] }
maplibre    = { git = "https://github.com/ar-puuk/maplibre-rs", rev = "336958cc19da19f105be4348132169cbbb0dbc9c", features = ["headless"] }
cgmath      = "0.18.0"
tokio       = { workspace = true }
reqwest     = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
thiserror   = { workspace = true }
prost       = { workspace = true }
image       = { workspace = true }
once_cell   = { workspace = true }
log         = { workspace = true }
pollster    = { workspace = true }

[dev-dependencies]
httptest    = "0.15"
tokio       = { workspace = true }

[[example]]
name = "headless_render"

[dev-dependencies.clap]
version  = "4"
features = ["derive"]
